// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignageLivePlayer.Api.Data.Db;

#nullable disable

namespace SignageLivePlayer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckInFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerUniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "9f50f77b-9ca2-4bd5-bcfa-571753efb640",
                            CheckInFrequency = 60,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(7610),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(7611),
                            PlayerName = "Reception Large Screen",
                            PlayerUniqueId = "RECEPT-0987",
                            SiteId = "ed1d40d2-a23a-4c49-a2db-9ac21ac3c07f"
                        },
                        new
                        {
                            Id = "b4052722-99ed-4ffe-81ab-0d1cd923478b",
                            CheckInFrequency = 60,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(571),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(572),
                            PlayerName = "Reception Small Screen 1",
                            PlayerUniqueId = "RECEPT-1273",
                            SiteId = "ed1d40d2-a23a-4c49-a2db-9ac21ac3c07f"
                        },
                        new
                        {
                            Id = "0db5c8aa-8f41-41b7-ba7a-1bda237fae3f",
                            CheckInFrequency = 60,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(609),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(610),
                            PlayerName = "Reception Small Screen 2",
                            PlayerUniqueId = "RECEPT-1986",
                            SiteId = "ed1d40d2-a23a-4c49-a2db-9ac21ac3c07f"
                        },
                        new
                        {
                            Id = "42ecce60-c4e7-4849-b6c8-f0ecbee4a699",
                            CheckInFrequency = 120,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(632),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(632),
                            PlayerName = "Sales Office",
                            PlayerUniqueId = "SALESO-5459",
                            SiteId = "ed1d40d2-a23a-4c49-a2db-9ac21ac3c07f"
                        },
                        new
                        {
                            Id = "a76fe79b-aa76-427d-a0d5-b1e668e44698",
                            CheckInFrequency = 180,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(653),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(654),
                            PlayerName = "Marketing Office 1",
                            PlayerUniqueId = "MARKET-2278",
                            SiteId = "33c842e3-5b4e-41ba-aa26-21d4e8d1f48b"
                        },
                        new
                        {
                            Id = "3fc0432f-0ab3-4243-ac2c-78e10db73ec3",
                            CheckInFrequency = 100,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(678),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(678),
                            PlayerName = "Marketing Office 2",
                            PlayerUniqueId = "MARKET-3424",
                            SiteId = "33c842e3-5b4e-41ba-aa26-21d4e8d1f48b"
                        },
                        new
                        {
                            Id = "4d348e46-3363-403e-869a-dbd183e8a1ec",
                            CheckInFrequency = 30,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(698),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(699),
                            PlayerName = "Warehouse Building 1",
                            PlayerUniqueId = "WAREHO-3751",
                            SiteId = "fc841305-958b-4ce9-b0f6-a01467fca116"
                        },
                        new
                        {
                            Id = "75d3cef6-7ec6-4d35-941e-58651f761118",
                            CheckInFrequency = 30,
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(719),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 456, DateTimeKind.Utc).AddTicks(719),
                            PlayerName = "Warehouse Building 2",
                            PlayerUniqueId = "WAREHO-7364",
                            SiteId = "fc841305-958b-4ce9-b0f6-a01467fca116"
                        });
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            RoleName = "SITEADMIN"
                        },
                        new
                        {
                            Id = "3",
                            RoleName = "USER"
                        });
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.Site", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SitePostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTown")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = "ed1d40d2-a23a-4c49-a2db-9ac21ac3c07f",
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(3188),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(3196),
                            SiteAddress1 = "30 South Street",
                            SiteAddress2 = "",
                            SiteCountry = "",
                            SiteCounty = "",
                            SiteName = "Headquarters",
                            SitePostcode = "CB85 1RA",
                            SiteTown = "Cambridge"
                        },
                        new
                        {
                            Id = "33c842e3-5b4e-41ba-aa26-21d4e8d1f48b",
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(5859),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(5861),
                            SiteAddress1 = "58 Grove Road",
                            SiteAddress2 = "",
                            SiteCountry = "",
                            SiteCounty = "",
                            SiteName = "London Branch",
                            SitePostcode = "CB85 1RA",
                            SiteTown = "East Central London"
                        },
                        new
                        {
                            Id = "fc841305-958b-4ce9-b0f6-a01467fca116",
                            DateCreated = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(5878),
                            DateModified = new DateTime(2024, 2, 25, 2, 20, 27, 455, DateTimeKind.Utc).AddTicks(5878),
                            SiteAddress1 = "54 York Road",
                            SiteAddress2 = "",
                            SiteCountry = "",
                            SiteCounty = "",
                            SiteName = "Manchester Branch",
                            SitePostcode = "M52 3RK",
                            SiteTown = "Manchester"
                        });
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "29c183f5-054d-45ef-a5a9-7046562be1f3",
                            Email = "admin",
                            FirstName = "",
                            LastName = "",
                            Password = "admin"
                        },
                        new
                        {
                            Id = "877cd4eb-2c99-4166-8945-8904a3233bdc",
                            Email = "user",
                            FirstName = "",
                            LastName = "",
                            Password = "user"
                        },
                        new
                        {
                            Id = "c43662b0-1fdb-44a1-8873-182a1b4f6865",
                            Email = "siteadmin",
                            FirstName = "",
                            LastName = "",
                            Password = "siteadmin"
                        });
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "29c183f5-054d-45ef-a5a9-7046562be1f3",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "29c183f5-054d-45ef-a5a9-7046562be1f3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "29c183f5-054d-45ef-a5a9-7046562be1f3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "877cd4eb-2c99-4166-8945-8904a3233bdc",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c43662b0-1fdb-44a1-8873-182a1b4f6865",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "c43662b0-1fdb-44a1-8873-182a1b4f6865",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.Player", b =>
                {
                    b.HasOne("SignageLivePlayer.Api.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SignageLivePlayer.Api.Data.Models.UserRole", b =>
                {
                    b.HasOne("SignageLivePlayer.Api.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
